import Photo from "./nik-owens-40OJLYVWeeM-unsplash.jpg";

const content = document.querySelector("#content");

const figure = document.createElement("figure");
const img = new Image();
img.src = Photo;
figure.appendChild(img);
const figcaption = document.createElement("figcaption");
figcaption.innerHTML =
  'Photo by <a href="https://unsplash.com/@nik_owens?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Nik Owens</a> on <a href="https://unsplash.com/photos/pizza-on-brown-wooden-table-40OJLYVWeeM?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>';
figure.appendChild(figcaption);
content.appendChild(figure);

const h1 = document.createElement("h1");
h1.textContent = "Mario's Italian Restaurant";
content.appendChild(h1);

let comment = document.createComment(
  "The following paragraph was generated by ChatGPT with the prompt \"Write a small paragraph-long promotional description for Mario's Italian Restaurant. Where Mario is secretly the Nintendo's iconic videogame character.\"",
);
content.appendChild(comment);
let p = document.createElement("p");
p.textContent =
  "Welcome to Mario's Italian Restaurant, where every dish is crafted with the same passion and precision as a level in one of Nintendo's classic games. Nestled in the heart of New York, Mario's brings the beloved flavors of Italy to your table, all under the watchful eye of our very own mustachioed maestro, Mario himself. From piping hot pizzas straight out of our brick oven to sumptuous pasta dishes bursting with flavor, every bite at Mario's is a culinary adventure. So come join us and experience the magic of Mario's Italian Restaurant, where every meal is a power-up for your taste buds!";
content.appendChild(p);
